language: python

matrix:
  include:
    - name: "Python 3.6 on Linux"
      python: 3.6
      dist: xenial
    - name: "Python 3.6 on Windows"
      os: windows
      python: 3.6
      language: shell
      before_install: choco install python --version 3.6.8
      env: PATH=/c/Python36/:/c/Python36/Scripts:$PATH
# command to install dependencies
install: pip install -r requirements.txt
# command to run tests
script:
  - python -m unittest discover -p *_test.py
